apiVersion: v1
kind: Service
metadata:
  namespace: hugo
  name: hugo-gcp-cheatsheets
  labels:
    app: hugo-gcp-cheatsheets
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  #clusterIP: None
  selector:
    app: hugo-gcp-cheatsheets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hugo
  name: hugo-gcp-cheatsheets
  labels:
    app: hugo-gcp-cheatsheets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo-gcp-cheatsheets
  template:
    metadata:
      labels:
        app: hugo-gcp-cheatsheets
    spec:
      containers:
      - name: hugo-gcp-cheatsheets
        image: skaffold-hugo
        ports:
          - containerPort: 8080
        #port: 8080

# port 8080 not needed.
